services:
  ftp-server:
    image: stilliard/pure-ftpd
    container_name: local-ftp-server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - D:\DockerCompose\FTP\files:/home/testuser/
    environment:
      FTP_USER_NAME: testuser
      FTP_USER_PASS: testpass
      FTP_USER_HOME: /home/testuser      
    restart: unless-stopped
